# Generated by Django 4.1.7 on 2023-03-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_extendeduser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendeduser',
            name='email',
        ),
    ]
