# Generated by Django 4.1.7 on 2023-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0005_userform_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
