# Generated by Django 4.1.7 on 2023-03-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_alter_userform_email_alter_userform_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
